### ISSUE TITLE
cannot execute: git-upload-pack

### ISSUE THREAD

**Issue by flooose** [wizmer/syncorg#7]
Hi! I'm getting a TransportException with the message "cannot execute: git-upload-pack". I get this right at the very beginning while trying to set up ssh access to my server. Here's the stacktrace:

```
09-24 11:07:18.082 21626 22624 W System.err: org.eclipse.jgit.api.errors.TransportException: ssh://myuser@myserver.example.com/home/chris/org/: cannot execute: git-upload-pack '/home/chris/org/'
09-24 11:07:18.083 21626 22624 W System.err:    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:137)
09-24 11:07:18.083 21626 22624 W System.err:    at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178)
09-24 11:07:18.083 21626 22624 W System.err:    at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125)
09-24 11:07:18.083 21626 22624 W System.err:    at com.coste.syncorg.synchronizers.JGitWrapper$CloneGitRepoTask.doInBackground(JGitWrapper.java:310)
09-24 11:07:18.083 21626 22624 W System.err:    at com.coste.syncorg.synchronizers.JGitWrapper$CloneGitRepoTask.doInBackground(JGitWrapper.java:276)
09-24 11:07:18.083 21626 22624 W System.err:    at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-24 11:07:18.083 21626 22624 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-24 11:07:18.086 21626 22624 W System.err:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-24 11:07:18.086 21626 22624 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-24 11:07:18.086 21626 22624 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-24 11:07:18.086 21626 22624 W System.err:    at java.lang.Thread.run(Thread.java:818)
09-24 11:07:18.086 21626 22624 W System.err: Caused by: org.eclipse.jgit.errors.TransportException: ssh://chris@flooose.ddns.net/home/chris/org/: cannot execute: git-upload-pack '/home/chris/org/'
09-24 11:07:18.087 21626 22624 W System.err:    at org.eclipse.jgit.transport.TransportGitSsh.checkExecFailure(TransportGitSsh.java:173)
09-24 11:07:18.087 21626 22624 W System.err:    at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:272)
09-24 11:07:18.087 21626 22624 W System.err:    at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:147)
09-24 11:07:18.087 21626 22624 W System.err:    at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
09-24 11:07:18.087 21626 22624 W System.err:    at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
09-24 11:07:18.087 21626 22624 W System.err:    at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1104)
09-24 11:07:18.087 21626 22624 W System.err:    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
09-24 11:07:18.087 21626 22624 W System.err:    ... 10 more
09-24 11:07:18.087 21626 22624 W System.err: Caused by: java.io.IOException: bash: git-upload-pack: command not found
09-24 11:07:18.088 21626 22624 W System.err:    at org.eclipse.jgit.transport.TransportGitSsh.checkExecFailure(TransportGitSsh.java:172)
09-24 11:07:18.088 21626 22624 W System.err:    ... 16 more
09-24 11:07:18.140 21626 21626 W System.err: org.eclipse.jgit.api.errors.TransportException: ssh://chris@flooose.ddns.net/home/chris/org/: cannot execute: git-upload-pack '/home/chris/org/'
09-24 11:07:18.140 21626 21626 W System.err:    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:137)
09-24 11:07:18.140 21626 21626 W System.err:    at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178)
09-24 11:07:18.140 21626 21626 W System.err:    at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125)
09-24 11:07:18.140 21626 21626 W System.err:    at com.coste.syncorg.synchronizers.JGitWrapper$CloneGitRepoTask.doInBackground(JGitWrapper.java:310)
09-24 11:07:18.140 21626 21626 W System.err:    at com.coste.syncorg.synchronizers.JGitWrapper$CloneGitRepoTask.doInBackground(JGitWrapper.java:276)
09-24 11:07:18.140 21626 21626 W System.err:    at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-24 11:07:18.141 21626 21626 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-24 11:07:18.141 21626 21626 W System.err:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-24 11:07:18.141 21626 21626 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-24 11:07:18.141 21626 21626 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-24 11:07:18.141 21626 21626 W System.err:    at java.lang.Thread.run(Thread.java:818)
09-24 11:07:18.141 21626 21626 W System.err: Caused by: org.eclipse.jgit.errors.TransportException: ssh://chris@flooose.ddns.net/home/chris/org/: cannot execute: git-upload-pack '/home/chris/org/'
09-24 11:07:18.141 21626 21626 W System.err:    at org.eclipse.jgit.transport.TransportGitSsh.checkExecFailure(TransportGitSsh.java:173)
09-24 11:07:18.141 21626 21626 W System.err:    at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:272)
09-24 11:07:18.141 21626 21626 W System.err:    at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:147)
09-24 11:07:18.141 21626 21626 W System.err:    at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
09-24 11:07:18.141 21626 21626 W System.err:    at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
09-24 11:07:18.141 21626 21626 W System.err:    at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1104)
09-24 11:07:18.141 21626 21626 W System.err:    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
09-24 11:07:18.141 21626 21626 W System.err:    ... 10 more
09-24 11:07:18.141 21626 21626 W System.err: Caused by: java.io.IOException: bash: git-upload-pack: command not found
09-24 11:07:18.142 21626 21626 W System.err:    at org.eclipse.jgit.transport.TransportGitSsh.checkExecFailure(TransportGitSsh.java:172)
09-24 11:07:18.142 21626 21626 W System.err:    ... 16 more
0
```

I've cloned the project and verified that this error is happening on the master branch as well. Let me know how I can help get this fixed.

**Comment by flooose** [comment]
I've got it fixed. I just saw that my server didn't have git installed. Would you consider a pull request to give a more informative error message. I was under the impression that the command `git-upload-pack` was expected to be found on my android device.

**Comment by wizmer** [comment]
Yes, sure !
From what I can see you managed to build the project. Did you had any issue
for this or was it straightforward ?

**Comment by flooose** [comment]
Very straight forward! I followed the instructions and everything worked out of the box. Thanks for the hard work on this.
